### ISSUE TITLE
input format

### ISSUE THREAD

**Issue by trojandodo** [airalcorn2/Recurrent-Convolutional-Neural-Network-Text-Classifier#1]
Hi,
In your code you don't specify how you embed the sentence / document and there's no use of word2vec , aside of indicating the embedding size. I imagine the part
doc_as_array = np.array([[1, 2, 3, 4]])
left_context_as_array = np.array([[MAX_TOKENS, 1, 2, 3]])
right_context_as_array = np.array([[2, 3, 4, MAX_TOKENS]])
is merely an example - but how do you actually go about embedding and feeding a sentence or document to the network?

Thanks

**Comment by airalcorn2** [comment]
Hi, @trojandodo. I've added some code that shows how you can convert a raw string into a sequence of integers corresponding to embeddings in a word2vec matrix. The code assumes you already have a word2vec model trained with gensim. The sequence of integers can then be fed directly into the model for training because the model uses an Embedding layer. Let me know if that answers your question.

**Comment by trojandodo** [comment]
Thanks Michael,
I appreciate this very much. I saw the update and now it's much clearer
what was the intention.
Best,
Ydo
